// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Schedule struct {
	ScheduleTime int32  `json:"schedule_time"`
	UserID       string `json:"user_id"`
	Message      string `json:"message"`
}
