// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	DeleteSchedule(ctx context.Context, scheduleTime int32) error
	GetSchedule(ctx context.Context, scheduleTime int32) (Schedule, error)
}

var _ Querier = (*Queries)(nil)
